# Export ALL app data from local Postgres into seed.sql (commit so teammates share the same rows).
#
# Usage (from repo root, with docker compose Postgres running):
#   powershell -File scripts/export-seed.ps1
#   npm run db:export-seed

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root "backend\src\main\resources\seed.sql"
$container = "aives-postgres"
$remoteDump = "/tmp/aives-seed-dump.sql"

$running = docker ps --filter "name=$container" --format "{{.Names}}"
if (-not $running) {
  Write-Error "Container '$container' is not running. Start it with: docker compose up -d"
}

# Dump inside the container (UTF-8 safe), then copy out.
# role + language_config stay in schema.sql.
$tables = @(
  '"user"',
  "course",
  "course_assignment",
  "enrollment",
  "rubric",
  "rubric_criterion",
  "course_document",
  "knowledge_chunk",
  "ai_generation_request",
  "question",
  "question_source_chunk",
  "exam_session",
  "exam_session_question",
  "exam_attempt",
  "question_turn",
  "answer"
)

$tableArgs = ($tables | ForEach-Object { "--table=$_" }) -join " "

Write-Host "Dumping ALL data tables from $container ..."
docker exec $container sh -c "pg_dump -U aives -d aives --data-only --column-inserts --rows-per-insert=50 $tableArgs > $remoteDump"
if ($LASTEXITCODE -ne 0) {
  Write-Error "pg_dump failed"
}

$tmpDump = Join-Path $env:TEMP "aives-seed-dump.sql"
docker cp "${container}:${remoteDump}" $tmpDump
if ($LASTEXITCODE -ne 0) {
  Write-Error "docker cp failed"
}

$dump = [System.IO.File]::ReadAllText($tmpDump, [System.Text.UTF8Encoding]::new($false))

$cleaned = ($dump -split "`r?`n" | Where-Object {
  $_ -notmatch '^\s*--' -and
  $_ -notmatch '^\s*SET ' -and
  $_ -notmatch '^\s*SELECT pg_catalog' -and
  $_ -notmatch '^\s*\\.' -and
  $_.Trim() -ne ''
}) -join "`n"

$cleaned = [regex]::Replace($cleaned, '\);(\s*)(?=(INSERT INTO|\z))', ");`nON CONFLICT DO NOTHING;`$1")

$header = @"
-- Generated by scripts/export-seed.ps1 from the local aives database.
-- Loaded once on an empty volume by SchemaInitializer (after schema.sql).
-- role + language_config come from schema.sql. Copy data/documents separately if you need uploaded files.

"@

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($out, $header + $cleaned + "`n", $utf8NoBom)
Write-Host "Wrote $out ($((Get-Item $out).Length) bytes)"
Write-Host "Review, then commit backend/src/main/resources/seed.sql"
