#!/usr/bin/env bash
# Export app data from local Postgres into seed.sql (commit so teammates share the same rows).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/backend/src/main/resources/seed.sql"
CONTAINER="${AIVES_PG_CONTAINER:-aives-postgres}"

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  echo "Container '$CONTAINER' is not running. Start it with: docker compose up -d" >&2
  exit 1
fi

TABLES=(
  '"user"'
  course
  course_assignment
  enrollment
  rubric
  rubric_criterion
  question
  exam_session
  exam_session_question
  exam_attempt
  question_turn
  answer
)

ARGS=()
for t in "${TABLES[@]}"; do
  ARGS+=(--table="$t")
done

echo "Dumping data from $CONTAINER ..."
DUMP="$(docker exec "$CONTAINER" pg_dump -U aives -d aives --data-only --column-inserts --rows-per-insert=100 "${ARGS[@]}")"

{
  cat <<'EOF'
-- Generated by scripts/export-seed.sh — commit this file so teammates get the same rows
-- on first empty-database boot (SchemaInitializer).
-- Uploaded PDF/DOCX and knowledge_chunk embeddings are NOT included.

EOF
  echo "$DUMP" | sed '/^INSERT INTO/ s/;[[:space:]]*$/\nON CONFLICT DO NOTHING;/'
} > "$OUT"

echo "Wrote $OUT"
