# Export app data from local Postgres into a SQL seed file you can commit.
# After commit + push, teammates who pull and start a fresh DB get the same demo rows.
#
# Usage (from repo root, with docker compose Postgres running):
#   powershell -File scripts/export-seed.ps1
#   npm run db:export-seed
#
# Does NOT include uploaded files or embedding chunks (those need the files on disk).

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root "backend\src\main\resources\seed.sql"
$container = "aives-postgres"

$running = docker ps --filter "name=$container" --format "{{.Names}}"
if (-not $running) {
  Write-Error "Container '$container' is not running. Start it with: docker compose up -d"
}

$tables = @(
  '"user"',
  "course",
  "course_assignment",
  "enrollment",
  "rubric",
  "rubric_criterion",
  "question",
  "exam_session",
  "exam_session_question",
  "exam_attempt",
  "question_turn",
  "answer"
)

$tableArgs = @()
foreach ($t in $tables) {
  $tableArgs += "--table=$t"
}

Write-Host "Dumping data from $container ..."
$dump = docker exec $container pg_dump -U aives -d aives --data-only --column-inserts --rows-per-insert=100 @tableArgs
if ($LASTEXITCODE -ne 0) {
  Write-Error "pg_dump failed"
}

# Convert plain INSERTs into idempotent seed statements for local reloads.
$lines = $dump -split "`n" | ForEach-Object {
  $line = $_
  if ($line -match '^INSERT INTO') {
    if ($line -match ';\s*$') {
      $line = $line -replace ';\s*$', "`nON CONFLICT DO NOTHING;"
    }
  }
  $line
}

$header = @"
-- Generated by scripts/export-seed.ps1 — commit this file so teammates get the same rows
-- on first empty-database boot (SchemaInitializer). Password hashes are as stored in your DB.
-- Demo password for original accounts is usually Password123 unless you changed them.
-- Uploaded PDF/DOCX and knowledge_chunk embeddings are NOT included.

"@

Set-Content -Path $out -Value ($header + ($lines -join "`n")) -Encoding utf8
Write-Host "Wrote $out"
Write-Host "Commit backend/src/main/resources/seed.sql and push. Teammates: docker compose up -d then mvn spring-boot:run on an empty volume."
