#!/usr/bin/env bash
# Export ALL app data from local Postgres into seed.sql.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/backend/src/main/resources/seed.sql"
CONTAINER="${AIVES_PG_CONTAINER:-aives-postgres}"

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
  echo "Container '$CONTAINER' is not running. Start it with: docker compose up -d" >&2
  exit 1
fi

TABLES=(
  '"user"'
  course
  course_assignment
  enrollment
  rubric
  rubric_criterion
  course_document
  knowledge_chunk
  ai_generation_request
  question
  question_source_chunk
  exam_session
  exam_session_question
  exam_attempt
  question_turn
  answer
)

ARGS=()
for t in "${TABLES[@]}"; do
  ARGS+=(--table="$t")
done

echo "Dumping ALL data tables from $CONTAINER ..."
DUMP="$(docker exec "$CONTAINER" pg_dump -U aives -d aives --data-only --column-inserts --rows-per-insert=50 "${ARGS[@]}")"

{
  cat <<'EOF'
-- Generated by scripts/export-seed.sh from the local aives database.
-- Loaded once on an empty volume by SchemaInitializer (after schema.sql).
-- role + language_config come from schema.sql. Physical upload files are not in Git.

EOF
  echo "$DUMP" \
    | grep -vE '^(--|SET |SELECT pg_catalog|\\.)' \
    | sed '/^INSERT INTO/ s/;[[:space:]]*$/\nON CONFLICT DO NOTHING;/'
} > "$OUT"

echo "Wrote $OUT ($(wc -c < "$OUT") bytes)"
