-- Generated by scripts/export-seed.ps1 â€” commit this file so teammates get the same rows
-- on first empty-database boot (SchemaInitializer). Password hashes are as stored in your DB.
-- Demo password for original accounts is usually Password123 unless you changed them.
-- Uploaded PDF/DOCX and knowledge_chunk embeddings are NOT included.
--
-- PostgreSQL database dump
--

\restrict g6zWov2Q3o7pFGM59uQrhqcP3yfqC2CQqc73ocQUok66iljsWwFrHRsDw3VCoOh

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg12+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: course; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.course (id, code, name, description, is_active, created_at) VALUES
	('c0000000-0000-0000-0000-000000000001', 'SWD392', 'Software Architecture and Design', 'Architecture styles, design patterns and documentation.', true, '2026-10-05 12:18:27.133002+00'),
	('c0000000-0000-0000-0000-000000000002', 'DBI202', 'Database Systems', 'Relational model, SQL and normalization.', true, '2026-10-05 12:18:27.133002+00'),
	('29c39f28-4606-47fd-b66c-4a72db569105', 'csd', 'giß║úi thuß║¡t', NULL, true, '2026-10-05 18:40:21.999281+00'),
	('912ac598-8abb-4329-8e9c-ea6471a68b21', 'se', 'it', NULL, true, '2026-10-06 04:44:31.629028+00'),
	('b001316e-4fbd-4d7e-9108-9c27e12675a1', 'NWC201', 'Networking', NULL, true, '2026-10-06 07:36:39.59181+00'),
	('4ec21e82-592f-4cba-b40f-2e02d797f3cc', 'DBI222', 'Database', NULL, true, '2026-10-06 08:11:15.563925+00');


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public."user" (id, email, password_hash, google_sub, full_name, student_code, role_id, is_active, last_login_at, created_at, updated_at) VALUES
	('a0000000-0000-0000-0000-000000000002', 'teacher@aives.test', '$2a$10$mTY2yyF3cBGT/T0ox6bWB.nkDy8OX.6EQ1fO16gTlaL5TRVVvy2zq', NULL, 'Nguyen Van An', NULL, 2, true, NULL, '2026-10-05 12:18:27.129332+00', '2026-10-05 12:18:27.129332+00'),
	('a0000000-0000-0000-0000-000000000003', 'student1@aives.test', '$2a$10$mTY2yyF3cBGT/T0ox6bWB.nkDy8OX.6EQ1fO16gTlaL5TRVVvy2zq', NULL, 'Tran Thi Binh', 'SE170001', 3, true, NULL, '2026-10-05 12:18:27.129332+00', '2026-10-05 12:18:27.129332+00'),
	('a0000000-0000-0000-0000-000000000004', 'student2@aives.test', '$2a$10$mTY2yyF3cBGT/T0ox6bWB.nkDy8OX.6EQ1fO16gTlaL5TRVVvy2zq', NULL, 'Le Van Cuong', 'SE170002', 3, true, NULL, '2026-10-05 12:18:27.129332+00', '2026-10-05 12:18:27.129332+00'),
	('a0000000-0000-0000-0000-000000000005', 'student3@aives.test', '$2a$10$mTY2yyF3cBGT/T0ox6bWB.nkDy8OX.6EQ1fO16gTlaL5TRVVvy2zq', NULL, 'Pham Thi Dung', 'SE170003', 3, true, NULL, '2026-10-05 12:18:27.129332+00', '2026-10-05 12:18:27.129332+00'),
	('eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'vohoanglong0002@gmail.com', NULL, '102454342640211946398', 'Ho├áng long V├╡', NULL, 2, true, NULL, '2026-10-05 12:24:58.091908+00', '2026-10-05 12:24:58.091908+00'),
	('a0000000-0000-0000-0000-000000000001', 'admin@aives.test', '$2a$10$mTY2yyF3cBGT/T0ox6bWB.nkDy8OX.6EQ1fO16gTlaL5TRVVvy2zq', NULL, 'Admin AIVES', NULL, 1, true, NULL, '2026-10-05 12:18:27.129332+00', '2026-10-05 12:18:27.129332+00'),
	('61489f13-bfad-4a5d-8699-2fea4413c52a', 'teacher@123gmail.com', '$2a$10$9C4ywIguIHZfZOOAAJpmMuP/fz7RWjxdrgtBjIFMZZvUYXmmSV7RG', NULL, 'c├┤longlanh', NULL, 2, true, NULL, '2026-10-05 17:39:11.510688+00', '2026-10-05 17:39:11.510688+00'),
	('919dbf5b-e6ac-424e-ac1a-daddb62f79aa', 'duyenntmse183135@fpt.edu.vn', NULL, '100266886607558949305', 'Nguyen Thi My Duyen', NULL, 3, true, NULL, '2026-10-05 17:38:11.821527+00', '2026-10-05 17:38:11.821527+00');


--
-- Data for Name: exam_session; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.exam_session (id, course_id, teacher_id, language_config_id, title, status, format, scheduled_at, duration_minutes, main_question_count, max_follow_ups, answer_time_limit_sec, created_at) VALUES
	('f0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000002', 'SWD392 Midterm Viva', 'PUBLISHED', 'ORAL', '2026-10-12 12:18:27.153067+00', 30, 2, 2, 120, '2026-10-05 12:18:27.153067+00'),
	('f0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'DBI202 Practice Viva', 'DRAFT', 'ORAL', NULL, 20, 2, 1, 90, '2026-10-05 12:18:27.153067+00'),
	('44f314df-cf26-4ce6-8893-9842eef3e143', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '00000000-0000-0000-0000-000000000001', 'NWC15p', 'IN_PROGRESS', 'ORAL', NULL, NULL, 3, 2, 120, '2026-10-06 07:59:06.056588+00');


--
-- Data for Name: exam_attempt; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.exam_attempt (id, session_id, student_id, status, started_at, submitted_at, score) VALUES
	('90000000-0000-0000-0000-000000000001', 'f0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000003', 'SUBMITTED', '2026-10-04 12:18:27.159981+00', '2026-10-04 12:30:27.159981+00', 80),
	('2265cf72-baed-44c8-97d9-bd3e8acf885d', '44f314df-cf26-4ce6-8893-9842eef3e143', '919dbf5b-e6ac-424e-ac1a-daddb62f79aa', 'IN_PROGRESS', '2026-10-06 08:06:13.781452+00', NULL, NULL);


--
-- Data for Name: rubric; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.rubric (id, course_id, name, description, created_by, created_at) VALUES
	('b0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000001', 'Oral viva rubric', 'Default rubric for oral questions.', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.141879+00'),
	('b0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000002', 'Oral viva rubric', 'Default rubric for oral questions.', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.141879+00'),
	('9a8a7b8f-f133-4310-9458-bba6272c0883', '29c39f28-4606-47fd-b66c-4a72db569105', 'Oral clarity', 'Default rubric for oral answers', '61489f13-bfad-4a5d-8699-2fea4413c52a', '2026-10-05 18:40:21.999281+00'),
	('1b25ca87-876e-4ec4-878e-0a4b22c6496f', '912ac598-8abb-4329-8e9c-ea6471a68b21', 'Oral clarity', 'Default rubric for oral answers', '61489f13-bfad-4a5d-8699-2fea4413c52a', '2026-10-06 04:44:31.629028+00'),
	('668e1983-8742-4108-88ae-619bf1e2014f', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', 'Oral clarity', 'Default rubric for oral answers', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:36:39.59181+00'),
	('2d02d915-56b9-4cd2-afa5-249e25ac9cac', '4ec21e82-592f-4cba-b40f-2e02d797f3cc', 'Oral clarity', 'Default rubric for oral answers', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 08:11:15.563925+00');


--
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.question (id, course_id, rubric_id, generation_id, topic, prompt, expected_answer, source_ref, key_points, bloom_level, status, source, author_id, reviewed_by, reviewed_at, created_at, updated_at) VALUES
	('e0000000-0000-0000-0000-000000000002', 'c0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', NULL, 'Architecture styles', 'Compare layered architecture with microservices.', 'Layered is simpler to build and deploy as one unit. Microservices scale and deploy independently but add operational and network complexity.', NULL, 'monolith vs distributed, independent deployment, complexity trade-off', 'ANALYZE', 'APPROVED', 'MANUAL', 'a0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00'),
	('e0000000-0000-0000-0000-000000000003', 'c0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', NULL, 'SOLID', 'What does the Dependency Inversion Principle say?', 'High-level modules should not depend on low-level modules. Both should depend on abstractions.', NULL, 'abstractions, high-level vs low-level, decoupling', 'REMEMBER', 'PENDING_REVIEW', 'AI', 'a0000000-0000-0000-0000-000000000002', NULL, NULL, '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00'),
	('e0000000-0000-0000-0000-000000000004', 'c0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000002', NULL, 'Normalization', 'Why do we normalize a database to third normal form?', 'To reduce redundancy and avoid update, insert and delete anomalies by removing partial and transitive dependencies.', NULL, 'redundancy, anomalies, transitive dependency', 'UNDERSTAND', 'APPROVED', 'MANUAL', 'a0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00'),
	('e0000000-0000-0000-0000-000000000005', 'c0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000002', NULL, 'SQL', 'When would you choose a LEFT JOIN instead of an INNER JOIN?', 'Use LEFT JOIN when rows from the left table must be kept even without a match in the right table.', NULL, 'keep unmatched rows, null values, reporting', 'APPLY', 'APPROVED', 'IMPORT', 'a0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00'),
	('e0000000-0000-0000-0000-000000000006', 'c0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', NULL, 'MVC', 'Trong m├┤ h├¼nh MVC, vai tr├▓ cß╗ºa Controller l├á g├¼?', 'Controller nhß║¡n input tß╗½ ng╞░ß╗¥i d├╣ng, gß╗ìi Model xß╗¡ l├╜ dß╗» liß╗çu v├á chß╗ìn View ─æß╗â hiß╗ân thß╗ï kß║┐t quß║ú.', NULL, '─æiß╗üu phß╗æi luß╗ông, t├ích biß╗çt giao diß╗çn v├á logic', 'REMEMBER', 'APPROVED', 'MANUAL', 'a0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00'),
	('e0000000-0000-0000-0000-000000000007', 'c0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', NULL, 'Clean architecture', 'So s├ính Clean Architecture vß╗¢i kiß║┐n tr├║c ph├ón lß╗¢p truyß╗ün thß╗æng khi dß╗▒ ├ín cß║ºn mß╗ƒ rß╗Öng theo domain.', 'Clean Architecture ─æß║╖t business rules ß╗ƒ trung t├óm v├á phß╗Ñ thuß╗Öc h╞░ß╗¢ng v├áo trong; ph├ón lß╗¢p truyß╗ün thß╗æng dß╗à bß╗ï r├áng buß╗Öc chß║╖t giß╗»a UI, service v├á persistence.', NULL, 'dependency rule, domain ß╗ƒ core, ─æß╗òi UI/DB ├¡t ß║únh h╞░ß╗ƒng logic', 'ANALYZE', 'APPROVED', 'MANUAL', 'a0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00'),
	('e0000000-0000-0000-0000-000000000008', 'c0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', NULL, 'SOLID', 'Cho v├¡ dß╗Ñ c├ích ├íp dß╗Ñng Open/Closed Principle khi th├¬m loß║íi b├ío c├ío mß╗¢i.', '─Éß╗ïnh ngh─⌐a interface ReportExporter v├á th├¬m implementation mß╗¢i thay v├¼ sß╗¡a class c┼⌐ ─æang xß╗¡ l├╜ nhiß╗üu ─æß╗ïnh dß║íng.', NULL, 'interface, mß╗ƒ rß╗Öng kh├┤ng sß╗¡a code c┼⌐, strategy', 'APPLY', 'PENDING_REVIEW', 'AI', 'a0000000-0000-0000-0000-000000000002', NULL, NULL, '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00'),
	('e0000000-0000-0000-0000-000000000009', 'c0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000002', NULL, 'Indexing', 'Khi n├áo n├¬n tß║ío composite index v├á thß╗⌐ tß╗▒ cß╗Öt trong index c├│ ├╜ ngh─⌐a g├¼?', 'D├╣ng composite index khi truy vß║Ñn lß╗ìc/sß║»p xß║┐p theo nhiß╗üu cß╗Öt; cß╗Öt c├│ ─æß╗Ö chß╗ìn lß╗ìc cao hoß║╖c xuß║Ñt hiß╗çn trong WHERE n├¬n ─æß╗⌐ng tr╞░ß╗¢c.', NULL, 'leftmost prefix, selectivity, covering index', 'APPLY', 'APPROVED', 'MANUAL', 'a0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00', '2026-10-05 12:18:27.149038+00'),
	('e0000000-0000-0000-0000-000000000010', 'c0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000002', NULL, 'Transactions', 'Giß║úi th├¡ch bß╗æn thuß╗Öc t├¡nh ACID cß╗ºa giao dß╗ïch c╞í sß╗ƒ dß╗» liß╗çu.', 'Atomicity (all-or-nothing), Consistency (r├áng buß╗Öc ─æ╞░ß╗úc giß╗»), Isolation (giao dß╗ïch kh├┤ng thß║Ñy trß║íng th├íi trung gian cß╗ºa nhau), Durability (commit tß╗ôn tß║íi sau sß╗▒ cß╗æ).', NULL, 'atomic, consistent, isolated, durable', 'REMEMBER', 'PENDING_REVIEW', 'IMPORT', 'a0000000-0000-0000-0000-000000000002', '61489f13-bfad-4a5d-8699-2fea4413c52a', '2026-10-06 04:49:05.00482+00', '2026-10-05 12:18:27.149038+00', '2026-10-06 04:49:05.00482+00'),
	('e0000000-0000-0000-0000-000000000001', 'c0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', NULL, 'Design patterns', 'Explain the Singleton pattern and one risk of using it.', 'Singleton ensures a class has a single instance with a global access point. Risks include hidden global state and harder unit testing.', NULL, 'single instance, global access point, hidden state, testing difficulty', 'UNDERSTAND', 'APPROVED', 'MANUAL', 'a0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '2026-10-06 05:49:16.994211+00', '2026-10-05 12:18:27.149038+00', '2026-10-06 05:49:16.994211+00'),
	('76bbdbeb-ee3f-4ae1-9400-338a9c129dd0', 'c0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000002', '1c09a07f-fee3-44f9-ba2d-c381a9f0ed65', 'SQL joins', 'What does a SQL JOIN combine rows from?', NULL, 'aives-db.docx, page 1', NULL, 'REMEMBER', 'PENDING_REVIEW', 'AI', 'a0000000-0000-0000-0000-000000000002', NULL, NULL, '2026-10-06 07:56:37.755694+00', '2026-10-06 07:56:37.755694+00'),
	('416063fc-dffe-4b08-8f82-fbad3f389eb0', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'If a device cannot access the internet, outline the troubleshooting steps you would follow, referencing the definitions of IP configuration, gateway, DNS, and the use of ping.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:34.566622+00', '2026-10-06 07:58:13.384497+00', '2026-10-06 07:58:34.566622+00'),
	('ba401e48-91b8-490e-9a73-0c4a6a62e8cd', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'Describe the process a browser follows to load a website when you type "example.com" into the address bar, incorporating the definitions of DNS, HTTP/HTTPS, and the steps outlined in the passage.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:34.729026+00', '2026-10-06 07:58:13.379763+00', '2026-10-06 07:58:34.729026+00'),
	('77d1b3ff-c7a6-4778-8b02-13dec3b1f424', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'A server is configured to listen on port 443. Using the definitions of port numbers and HTTP/HTTPS, explain which protocol is likely being used and why.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:34.868979+00', '2026-10-06 07:58:13.375137+00', '2026-10-06 07:58:34.868979+00'),
	('a6359095-2062-492d-8698-20fe4240977f', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'Compare and contrast the functions of a hub and a switch, and explain why a switch is typically preferred in modern LANs, based on the passage.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:35.004721+00', '2026-10-06 07:58:13.370188+00', '2026-10-06 07:58:35.004721+00'),
	('8a58d901-9def-4532-99b5-2a5b1a953959', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'A network uses a default gateway of 192.168.1.1. Explain what happens when a host sends traffic to a destination outside its local network, using the definition of default gateway.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:35.165631+00', '2026-10-06 07:58:13.36362+00', '2026-10-06 07:58:35.165631+00'),
	('8ec75bfd-c032-4725-9416-6c8317f723d7', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'If a packet is lost during transmission, describe the steps you would take to troubleshoot the issue, referencing the definitions of packet loss and ping.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:35.320245+00', '2026-10-06 07:58:13.358718+00', '2026-10-06 07:58:35.320245+00'),
	('dd12842e-36a1-43dc-acbd-d6e244bbc6a9', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'Given a device with IP address 10.0.0.5 and subnet mask 255.0.0.0, determine the network address and the range of host addresses using the definitions of subnet mask and IP address from the passage.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:35.480119+00', '2026-10-06 07:58:13.352471+00', '2026-10-06 07:58:35.480119+00'),
	('924b5365-8e11-4a05-995f-c5acbcd55a87', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'Explain the difference between TCP and UDP and provide a scenario where each protocol would be the appropriate choice, based on the definitions provided.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:32.519197+00', '2026-10-06 07:58:13.399223+00', '2026-10-06 07:58:32.519197+00'),
	('4c7628c5-036c-459a-8f34-98396a031306', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'Given a network with high latency, explain how this impacts real-time applications such as VoIP, using the definition of latency.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:34.272471+00', '2026-10-06 07:58:13.393053+00', '2026-10-06 07:58:34.272471+00'),
	('e7e7d28b-1146-48fd-a145-bd8dbc6779cb', 'b001316e-4fbd-4d7e-9108-9c27e12675a1', '668e1983-8742-4108-88ae-619bf1e2014f', '16a680f7-1e06-43a6-8891-0d68deb6208d', 'Oral reasoning', 'Explain how NAT allows multiple devices in a private network to share a single public IP address, using the definition of NAT from the passage.', NULL, '30_networking_questions_answers.docx, page 1', NULL, 'APPLY', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:58:34.427185+00', '2026-10-06 07:58:13.388795+00', '2026-10-06 07:58:34.427185+00'),
	('1d3aad37-036d-459f-b7d0-82b59a76be52', '4ec21e82-592f-4cba-b40f-2e02d797f3cc', '2d02d915-56b9-4cd2-afa5-249e25ac9cac', '87f26bca-33aa-4689-8d13-ed742e816c32', 'Oral reasoning', 'Compare the WHERE and HAVING clauses in SQL with respect to when they are applied during query execution and the types of functions they can contain.', 'WHERE filters individual rows before any GROUP BY operation and cannot contain aggregate functions such as SUM, AVG, COUNT, MAX, MIN. HAVING filters groups after the GROUP BY has been performed and is typically used with aggregate functions.', '10_Cau_Hoi_Va_Dap_An_Database.docx, page 1', 'WHERE filters rows before GROUP BY; WHERE cannot contain aggregate functions; HAVING filters groups after GROUP BY; HAVING often contains aggregate functions', 'ANALYZE', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 08:35:59.246716+00', '2026-10-06 08:35:33.429355+00', '2026-10-06 08:35:59.246716+00'),
	('e8d8147f-4de1-4dd4-b67e-e17e49bbef36', '4ec21e82-592f-4cba-b40f-2e02d797f3cc', '2d02d915-56b9-4cd2-afa5-249e25ac9cac', '87f26bca-33aa-4689-8d13-ed742e816c32', 'Oral reasoning', 'Analyze the tradeΓÇæoffs of creating an index on a table: explain the performance benefits for read operations and the penalties for write operations.', 'An index (usually BΓÇæTree or Hash) speeds up data retrieval for WHERE, JOIN, and ORDER BY clauses by avoiding full table scans. However, it consumes extra disk/memory space and slows down INSERT, UPDATE, and DELETE operations because the index structure must be updated on each write.', '10_Cau_Hoi_Va_Dap_An_Database.docx, page 1', 'Index speeds up SELECT/WHERE/JOIN/ORDER BY; Index avoids full table scan; Index consumes extra storage; Index slows INSERT/UPDATE/DELETE due to maintenance', 'ANALYZE', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 08:36:00.768478+00', '2026-10-06 08:35:33.439535+00', '2026-10-06 08:36:00.768478+00'),
	('863111f9-5339-458b-a8bc-2ff263b24c28', '4ec21e82-592f-4cba-b40f-2e02d797f3cc', '2d02d915-56b9-4cd2-afa5-249e25ac9cac', '87f26bca-33aa-4689-8d13-ed742e816c32', 'Oral reasoning', 'A table uses a composite primary key. Explain why achieving Second Normal Form (2NF) is necessary and describe the specific anomaly it eliminates.', '2NF requires the table to be in 1NF and that every nonΓÇækey attribute be fully functionally dependent on the entire primary key, not just part of it. This removes partial dependency anomalies where a nonΓÇækey attribute depends on only a portion of the composite key, leading to redundancy and update anomalies.', '10_Cau_Hoi_Va_Dap_An_Database.docx, page 1', '2NF requires 1NF; nonΓÇækey attributes must depend on whole primary key; eliminates partial dependency; prevents redundancy and update anomalies', 'ANALYZE', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 08:36:02.052424+00', '2026-10-06 08:35:33.447562+00', '2026-10-06 08:36:02.052424+00'),
	('b3ff5603-c428-4dfe-8bf2-01789c80f6ba', '4ec21e82-592f-4cba-b40f-2e02d797f3cc', '2d02d915-56b9-4cd2-afa5-249e25ac9cac', '87f26bca-33aa-4689-8d13-ed742e816c32', 'Oral reasoning', 'Contrast the scaling approaches of relational (SQL) and nonΓÇærelational (NoSQL) databases and relate these approaches to their typical ACID compliance.', 'Relational databases use a fixed schema, enforce strong ACID properties, and scale vertically by adding more powerful hardware. NoSQL databases use flexible schemas (document, keyΓÇævalue, graph, wideΓÇæcolumn), often relax strict ACID for higher performance, and scale horizontally by adding more nodes.', '10_Cau_Hoi_Va_Dap_An_Database.docx, page 1', 'SQL: fixed schema, strong ACID, vertical scaling; NoSQL: flexible schema, relaxed ACID, horizontal scaling; SQL examples: MySQL, Oracle, SQL Server; NoSQL examples: MongoDB, Redis, Cassandra, Neo4j', 'ANALYZE', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 08:36:03.563347+00', '2026-10-06 08:35:33.453743+00', '2026-10-06 08:36:03.563347+00'),
	('ff89ae4c-6007-437a-aca7-4264971b8f27', '4ec21e82-592f-4cba-b40f-2e02d797f3cc', '2d02d915-56b9-4cd2-afa5-249e25ac9cac', '87f26bca-33aa-4689-8d13-ed742e816c32', 'Oral reasoning', 'A fundsΓÇætransfer transaction debits one account and credits another. Describe how each ACID property (Atomicity, Consistency, Isolation, Durability) protects the database if a crash occurs after the debit but before the credit.', 'Atomicity ensures the whole transfer either completes fully or is rolled back, so the debit alone cannot persist. Consistency guarantees the database moves from one valid state (balanced accounts) to another. Isolation prevents other concurrent transactions from seeing the intermediate debitΓÇæonly state. Durability ensures that once the transaction commits, both debit and credit survive any subsequent system failure.', '10_Cau_Hoi_Va_Dap_An_Database.docx, page 1', 'Atomicity: allΓÇæorΓÇænothing; Consistency: valid state to valid state; Isolation: concurrent transactions do not interfere; Durability: committed data persists after crash', 'ANALYZE', 'APPROVED', 'AI', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 08:36:05.870397+00', '2026-10-06 08:35:33.460373+00', '2026-10-06 08:36:05.870397+00');


--
-- Data for Name: question_turn; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.question_turn (id, attempt_id, question_id, parent_turn_id, turn_no, turn_type, follow_up_no, question_text, asked_at) VALUES
	('91000000-0000-0000-0000-000000000001', '90000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001', NULL, 1, 'MAIN', NULL, 'Explain the Singleton pattern and one risk of using it.', '2026-10-05 12:18:27.163177+00'),
	('91000000-0000-0000-0000-000000000002', '90000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001', '91000000-0000-0000-0000-000000000001', 2, 'FOLLOW_UP', 1, 'How would you make a Singleton easier to test?', '2026-10-05 12:18:27.163177+00');


--
-- Data for Name: answer; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.answer (id, turn_id, status, transcript, stt_confidence, duration_ms, needs_follow_up, follow_up_reason, stt_latency_ms, llm_latency_ms, answered_at) VALUES
	('92000000-0000-0000-0000-000000000001', '91000000-0000-0000-0000-000000000001', 'ANSWERED', 'Singleton keeps only one instance of a class and gives a global access point. The risk is that it hides global state.', 0.940, 21000, true, 'MISSING_POINT', NULL, NULL, '2026-10-05 12:18:27.167072+00'),
	('92000000-0000-0000-0000-000000000002', '91000000-0000-0000-0000-000000000002', 'ANSWERED', 'I would inject the instance through an interface so a test can replace it with a fake.', 0.910, 14000, false, NULL, NULL, NULL, '2026-10-05 12:18:27.167072+00');


--
-- Data for Name: course_assignment; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.course_assignment (course_id, teacher_id, assigned_at) VALUES
	('c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.135575+00'),
	('c0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000002', '2026-10-05 12:18:27.135575+00'),
	('c0000000-0000-0000-0000-000000000001', '61489f13-bfad-4a5d-8699-2fea4413c52a', '2026-10-05 18:21:11.040809+00'),
	('c0000000-0000-0000-0000-000000000002', '61489f13-bfad-4a5d-8699-2fea4413c52a', '2026-10-05 18:21:11.040809+00'),
	('29c39f28-4606-47fd-b66c-4a72db569105', '61489f13-bfad-4a5d-8699-2fea4413c52a', '2026-10-05 18:40:22.00866+00'),
	('912ac598-8abb-4329-8e9c-ea6471a68b21', '61489f13-bfad-4a5d-8699-2fea4413c52a', '2026-10-06 04:44:31.640116+00'),
	('b001316e-4fbd-4d7e-9108-9c27e12675a1', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 07:36:39.605646+00'),
	('4ec21e82-592f-4cba-b40f-2e02d797f3cc', 'eee1ace4-deae-4c16-bf6e-1a36a27b4afd', '2026-10-06 08:11:15.572156+00');


--
-- Data for Name: enrollment; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.enrollment (course_id, student_id, enrolled_at) VALUES
	('c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000003', '2026-10-05 12:18:27.138459+00'),
	('c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000004', '2026-10-05 12:18:27.138459+00'),
	('c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000005', '2026-10-05 12:18:27.138459+00'),
	('c0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000003', '2026-10-05 12:18:27.138459+00'),
	('c0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000004', '2026-10-05 12:18:27.138459+00');


--
-- Data for Name: exam_session_question; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.exam_session_question (session_id, question_id, sort_order) VALUES
	('f0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001', 1),
	('f0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000002', 2),
	('f0000000-0000-0000-0000-000000000002', 'e0000000-0000-0000-0000-000000000004', 1),
	('f0000000-0000-0000-0000-000000000002', 'e0000000-0000-0000-0000-000000000005', 2),
	('44f314df-cf26-4ce6-8893-9842eef3e143', '924b5365-8e11-4a05-995f-c5acbcd55a87', 1),
	('44f314df-cf26-4ce6-8893-9842eef3e143', 'e7e7d28b-1146-48fd-a145-bd8dbc6779cb', 2),
	('44f314df-cf26-4ce6-8893-9842eef3e143', '416063fc-dffe-4b08-8f82-fbad3f389eb0', 3),
	('44f314df-cf26-4ce6-8893-9842eef3e143', 'ba401e48-91b8-490e-9a73-0c4a6a62e8cd', 4),
	('44f314df-cf26-4ce6-8893-9842eef3e143', '77d1b3ff-c7a6-4778-8b02-13dec3b1f424', 5),
	('44f314df-cf26-4ce6-8893-9842eef3e143', 'a6359095-2062-492d-8698-20fe4240977f', 6),
	('44f314df-cf26-4ce6-8893-9842eef3e143', '8a58d901-9def-4532-99b5-2a5b1a953959', 7),
	('44f314df-cf26-4ce6-8893-9842eef3e143', '8ec75bfd-c032-4725-9416-6c8317f723d7', 8),
	('44f314df-cf26-4ce6-8893-9842eef3e143', '4c7628c5-036c-459a-8f34-98396a031306', 9),
	('44f314df-cf26-4ce6-8893-9842eef3e143', 'dd12842e-36a1-43dc-acbd-d6e244bbc6a9', 10);


--
-- Data for Name: rubric_criterion; Type: TABLE DATA; Schema: public; Owner: aives
--

INSERT INTO public.rubric_criterion (id, rubric_id, name, description, max_points, weight, sort_order) VALUES
	('d0000000-0000-0000-0000-000000000001', 'b0000000-0000-0000-0000-000000000001', 'Accuracy', 'Is the answer technically correct?', 4.00, 1.00, 1),
	('d0000000-0000-0000-0000-000000000002', 'b0000000-0000-0000-0000-000000000001', 'Completeness', 'Does it cover the key points?', 3.00, 1.00, 2),
	('d0000000-0000-0000-0000-000000000003', 'b0000000-0000-0000-0000-000000000001', 'Clarity', 'Is the explanation clear and well ordered?', 3.00, 1.00, 3),
	('d0000000-0000-0000-0000-000000000004', 'b0000000-0000-0000-0000-000000000002', 'Accuracy', 'Is the answer technically correct?', 4.00, 1.00, 1),
	('d0000000-0000-0000-0000-000000000005', 'b0000000-0000-0000-0000-000000000002', 'Completeness', 'Does it cover the key points?', 3.00, 1.00, 2),
	('d0000000-0000-0000-0000-000000000006', 'b0000000-0000-0000-0000-000000000002', 'Clarity', 'Is the explanation clear and well ordered?', 3.00, 1.00, 3),
	('37682e73-4f02-4bfe-a68a-0f090688b0d2', '9a8a7b8f-f133-4310-9458-bba6272c0883', 'Oral clarity', 'Answer is accurate, clear, and uses course terms.', 10.00, 1.00, 0),
	('9b37208d-403a-4c38-82bc-f7a1f10d1c14', '1b25ca87-876e-4ec4-878e-0a4b22c6496f', 'Oral clarity', 'Answer is accurate, clear, and uses course terms.', 10.00, 1.00, 0),
	('ceb33129-ff7a-4fe8-9df1-e9859d605c7f', '668e1983-8742-4108-88ae-619bf1e2014f', 'Oral clarity', 'Answer is accurate, clear, and uses course terms.', 10.00, 1.00, 0),
	('59ba9f4d-0af1-48b9-b9e6-e74d3ff9cdc9', '2d02d915-56b9-4cd2-afa5-249e25ac9cac', 'Oral clarity', 'Answer is accurate, clear, and uses course terms.', 10.00, 1.00, 0);


--
-- PostgreSQL database dump complete
--

\unrestrict g6zWov2Q3o7pFGM59uQrhqcP3yfqC2CQqc73ocQUok66iljsWwFrHRsDw3VCoOh

